services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb   # shared memory limit
    environment:
      POSTGRES_DB: madness-list-node-test
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
  cache:
    image: redis:8.6.1
    restart: always
    environment:
      - REDIS_PASSWORD=test_pass
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning